config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "result", to: "pages#result", as: "result"
  get '/reload_page', to: 'pages#reload_page', as: 'reload_page'
  get '/region', to: 'cheeses#region', as: 'region'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :cheeses, only: [:index, :map, :region, :show] do
    resources :reviews, only: [:new, :create]
    resources :bookmarks, only: [:create, :destroy]
    post "forbidden", to: "bookmarks#forbidden", as: "forbidden"
    delete "forbiddens/:id", to: "bookmarks#destroy", as: "destroy_forbiddens"
  end

  resources :bookmarks, only: [:index]

  get "userprofiles/question_1" => "userprofiles#question_1", as: "question_1"
  get "userprofiles/question_2" => "userprofiles#question_2", as: "question_2"
  get "userprofiles/question_3" => "userprofiles#question_3", as: "question_3"
  get "userprofiles/profil" => "userprofiles#show", as: "show"

  patch "userprofiles/question_1" => "userprofiles#update"
  patch "userprofiles/question_2" => "userprofiles#update"
  patch "userprofiles/question_3" => "userprofiles#update"
  patch "userprofiles/profil" => "userprofiles#update"
end

app/views/shared/_cheese_show_card.html.erb
<div id="cheese-card-show" data-slide-cards-target="card" data-action="click->slide-cards#user">
  <div id="top-card">
    <div class="logo-cheese-type">
      <h1><%= @cheese.name %></h1>
      <% if @cheese.filter_vache %>
      <%= image_tag "vache.png", id: "icons-cheese-type" %>
      <% elsif @cheese.filter_brebis %>
        <%= image_tag "brebis.png", id: "icons-cheese-type" %>
      <% else %>
        <%= image_tag "chevre.png", id: "icons-cheese-type" %>
      <% end %>
    </div>
    <%= image_tag @cheese.picture_url, class: "image-cheese-show" %>
  </div>
  <div id="bottom-card">
    <% if @cheese.filter_vache %>
      <h3 class="cheese-type"><strong> Fromage de vache </strong></h3>
    <% elsif @cheese.filter_brebis %>
      <h3 class="cheese-type"><strong> Fromage de brebis </strong></h3>
    <% else %>
      <h3 class="cheese-type"><strong> Fromage de chèvre </strong></h3>
    <% end %>
    <div class="parent-cheese-informations">
      <div class="cheese-informations">
        <%= image_tag "SVG/fromage_1.svg", id: "icons-cheese" %>
        <p><%= @cheese.pate %></p>
      </div>
    </div>
    <div class="parent-cheese-informations">
      <h4> <strong> Dégustation optimale </strong></h4>
      <div class="cheese-informations">
        <%= render "shared/season_loader" %>
        <p><%= @cheese.saison %></p>
      </div>

      <h4> <strong> Note moyenne : </strong> </h4>
      <div class="cheese-average-rating">
              <div class="d-flex" id="stars-bookmark-show">
                <% if @cheese.reviews.empty? %>
                  <div class="avis-text-show">
                  <%= "Il n'y a pas encore d'avis pour ce fromage" %>
                  </div>
                <% else %>
                  <% @cheese.average_rating_cheese.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - @cheese.average_rating_cheese).times do %>
                  <i class="far fa-star"></i>
                  <% end %>
                  <p class="avis-show-cheese"> <%= @cheese.reviews.count %> avis </p>
                <% end %>
                <%# <%= link_to "Lire les avis", bookmarks_path %>
              </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cheese_show_card_bookmarks.html.erb
<div id="cheese-card-show">
  <div id="top-card">
    <div class="logo-cheese-type">
      <h1><%= @cheese.name %></h1>
      <% if @cheese.filter_vache %>
      <%= image_tag "vache.png", id: "icons-cheese-type" %>
      <% elsif @cheese.filter_brebis %>
        <%= image_tag "brebis.png", id: "icons-cheese-type" %>
      <% else %>
        <%= image_tag "chevre.png", id: "icons-cheese-type" %>
      <% end %>
    </div>
    <%= image_tag @cheese.picture_url, class: "image-cheese-show" %>
  </div>
  <div id="bottom-card">
    <% if @cheese.filter_vache %>
      <h3 class="cheese-type"><strong> Fromage de vache </strong></h3>
    <% elsif @cheese.filter_brebis %>
      <h3 class="cheese-type"><strong> Fromage de brebis </strong></h3>
    <% else %>
      <h3 class="cheese-type"><strong> Fromage de chèvre </strong></h3>
    <% end %>
    <div class="parent-cheese-informations">
      <div class="cheese-informations">
        <%= image_tag "SVG/fromage_1.svg", id: "icons-cheese" %>
        <p><%= @cheese.pate %></p>
      </div>
    </div>
    <div class="parent-cheese-informations">

      <h4> <strong> Dégustation optimale </strong></h4>
      <div class="cheese-informations">
        <%= render "shared/season_loader" %>
        <p><%= @cheese.saison %></p>
      </div>

      <h4> <strong> Note moyenne : </strong> </h4>
      <div class="cheese-average-rating">
              <div class="d-flex" id="stars-bookmark-show">
                <% if @cheese.reviews.empty? %>
                  <div class="avis-text-show">
                  <%= "Il n'y a pas encore d'avis pour ce fromage" %>
                  </div>
                <% else %>
                  <% @cheese.average_rating_cheese.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - @cheese.average_rating_cheese).times do %>
                  <i class="far fa-star"></i>
                  <% end %>
                  <p class="avis-show-cheese"> <%= @cheese.reviews.count %> avis </p>
                <% end %>
                <%# <%= link_to "Lire les avis", bookmarks_path %>
              </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar-bottom-default.erb
<nav class="navbar-bottom">
    <%= link_to "", root_path, class: "fa-solid fa-house" %>
    <%= link_to "", bookmarks_path, class: "fa-solid fa-bookmark" %>
    <%= link_to "", show_path, class: "fa-solid fa-user" %>
</nav>

app/views/shared/_navbar-bottom-default.html.erb
<nav class="navbar-bottom">
  <%= link_to root_path, style: "text-decoration: none;" do  %>
    <%= image_tag "SVG/home.svg", width: '25px', id: "icon-cheese-home" %>
  <% end %>
  <%= link_to bookmarks_path, style: "text-decoration: none;" do  %>
    <%= image_tag "SVG/favourites.svg", width: '20px', id: "icon-cheese-home" %>
  <% end %>
  <%= link_to region_path, style: "text-decoration: none;" do  %>
    <%= image_tag "SVG/france.svg", width: '25px', height: '25px', id: "icon-france-profile" %>
  <% end %>
  <%= link_to show_path, style: "text-decoration: none;" do  %>
    <%= image_tag "SVG/user.svg", width: '25px', id: "icon-user-profile" %>
  <% end %>
</nav>

app/views/shared/_navbar-top-default.erb

<nav class="navbar-top" data-controller="navbar">
    <%= form_with url: cheeses_path, method: :get, id: "d-flexs" do %>
      <%= text_field_tag :query,params[:query],class: "form-control-navbar",placeholder: "Trouver votre fromage", data: { navbar_target: "value" }%>
      <i class="fa fa-search" data-action="click->navbar#display"></i>
    <% end %>
    <%= link_to root_path do %>
      <%= image_tag 'logo_simple.png', class: "logofrom", data: {navbar_target: "logo" }%>
    <% end %>

    <%# connecter l'icone à la méthode search %>
    <i class="fa-solid fa-bars" id="menu-icon"></i>
    <%# réaliser %>
</nav>

app/views/shared/_navbar-top-default.html.erb
<nav class="navbar-top" data-controller="navbar">
    <%= form_with url: cheeses_path, method: :get, id: "d-flexs" do %>
      <%= text_field_tag :query,params[:query],class: "form-control-navbar",placeholder: "Trouve ton fromage", data: { navbar_target: "value" }%>
      <i class="fa fa-search" data-action="click->navbar#display" data-navbar-target="btn"></i>
      <%= button_tag class: "d-none", id: "button-test", data: { navbar_target: "btn2" } do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>
    <%= link_to root_path do %>
      <%= image_tag 'logo_simple.png', class: "logofrom", data: {navbar_target: "logo" }%>
    <% end %>
    <i class="fa-solid fa-bars" id="menu-icon" data-action="click->navbar#displayLink" ></i>
    <div class="all_link" data-navbar-target="link">
    <%= link_to userprofiles_profil_path do %>
    <p class="lienn">Mon profil</p>
    <% end %>
    <%= link_to bookmarks_path do %>
    <p class="lienn">Mes envies</p>
    <% end %>
    <%= link_to destroy_user_session_path do %>
    <p class="lien">Déconnexion</p>
    <% end %>
    </div>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>

    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_season_loader.html.erb
<div class="season-loader">
  <% seasons = @cheese.saison %>
  <div class="hiver">
    <div class="carrée" style="background-color: <% if seasons["Hiver"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Hiver"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Hiver"] %> #11101E <% else %> #959599 <% end %>"></div>
  </div>
  <div class="printemps">
    <div class="carrée" style="background-color: <% if seasons["Printemps"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Printemps"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Printemps"] %> #11101E <% else %> #959599 <% end %>"></div>
  </div>
  <div class="été">
    <div class="carrée" style="background-color: <% if seasons["Eté"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Eté"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Eté"] %> #11101E <% else %> #959599 <% end %>"></div>
  </div>
  <div class="automne">
    <div class="carrée" style="background-color: <% if seasons["Automne"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Automne"] %> #11101E <% else %> #959599 <% end %>"></div>
    <div class="carrée" style="background-color: <% if seasons["Automne"] %> #11101E <% else %> #959599 <% end %>"></div>
  </div>
</div>