config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "result", to: "pages#result", as: "result"
  get '/reload_page', to: 'pages#reload_page', as: 'reload_page'
  get '/region', to: 'cheeses#region', as: 'region'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :cheeses, only: [:index, :map, :region, :show] do
    resources :reviews, only: [:new, :create]
    resources :bookmarks, only: [:create, :destroy]
    post "forbidden", to: "bookmarks#forbidden", as: "forbidden"
    delete "forbiddens/:id", to: "bookmarks#destroy", as: "destroy_forbiddens"
  end

  resources :bookmarks, only: [:index]

  get "userprofiles/question_1" => "userprofiles#question_1", as: "question_1"
  get "userprofiles/question_2" => "userprofiles#question_2", as: "question_2"
  get "userprofiles/question_3" => "userprofiles#question_3", as: "question_3"
  get "userprofiles/profil" => "userprofiles#show", as: "show"

  patch "userprofiles/question_1" => "userprofiles#update"
  patch "userprofiles/question_2" => "userprofiles#update"
  patch "userprofiles/question_3" => "userprofiles#update"
  patch "userprofiles/profil" => "userprofiles#update"
end

app/views/pages/home.html.erb
<%= render "shared/navbar-top-default" %>
<main class="content-middle homepage" data-controller="roulette infos">
    <div id="image-roulette">
      <div id="roulette-svg" data-roulette-target="svg">
        <%= image_tag("SVG/roulette.svg") %>
      </div>
    </div>
    <div class="search-roulette">
      <div data-roulette-target="parameters" class="d-none" id="form_roulette">
        <div data-action="click->roulette#close" id= "icons-cross-home">
          <%= image_tag "SVG/cross.svg" %>
        </div>
        <%= form_tag(result_path, method: :get, id: "form-home", data: { roulette_target: "form" }) do %>
          <div>
            <p class="text-center">Lait de :</p>
            <div class="d-flex justify-content-between">
              <%= check_box_tag :Vache, 1, true, class: "tag-selector" %>
              <%= label_tag :"Vache" %>
              <%= check_box_tag :Brebis, 1, true, class: "tag-selector" %>
              <%= label_tag :"Brebis" %>
              <%= check_box_tag :Chèvre, 1, true, class: "tag-selector" %>
              <%= label_tag :"Chèvre" %>
            </div>
          </div>
          <div>
            <p class="text-center mt-4">Produit uniquement :</p>
            <div class="d-flex justify-content-between">
              <%= check_box_tag :AOP, 0, false, class: "tag-selector" %>
              <%= label_tag :"AOP" %>

              <%= check_box_tag :pour_femme_enceinte, 0, false, class: "tag-selector" %>
              <%= label_tag :"pour femme enceinte" %>
            </div>
          </div>
            <%= button_tag :"Chercher un fromage", type: "button", id: "second-search", data: { action: "click->roulette#rotate" } %>
        <% end %>
      </div>
      <%= button_to 'Chercher un fromage', result_path, id: "fromage-search", class: "justify-content-center",  method: "get", params: {search_all: true}, data: { roulette_target: 'button', action: "click->roulette#rotateBis" } %>
      <button id= "personnaliser" data-action="click->roulette#display" data-roulette-target="btn2">Personnaliser ma recherche</button>
    </div>
    <div class="question" data-action="click->infos#infoSlide">
        <%= image_tag "SVG/question.svg", width: '45px', id:"help" %>
    </div>
    <div class="infoslide" data-infos-target="info">
      <div class="help">
        <%= image_tag "SVG/cross.svg", id: "icon-info", data: { action: "click->infos#slideOff"} %>
        <h2><strong>Pourquoi Frometon ?</strong></h2>
        <p>Frometon est ton assistant personnel, côté fromage ! <br>L’application te permet de trouver le produit qui te correspond.<br> Complète ton profil avec ton goût pour chaque type de fromage, ou personnalise directement ta recherche sur cette page. Frometon se charge du reste !</p>
      </div>
    </div>

</main>
<%= render "shared/navbar-bottom-default" %>

app/views/pages/result.html.erb
<%= render "shared/navbar-top-default" %>
<main class="content-middle homepage" data-turbo="false">
  <div id="cheese-result">
    <% if @cheese != [] && @cheese != nil %>
      <div id="cheese-result-card">
        <div class="d-flex" style="flex-direction: column;height: 150px;justify-content: space-evenly;">
          <h1><%= @cheese.name %></h1>
          <%= link_to "Voir ce fromage", cheese_path(@cheese) %>
        </div>
        <%= image_tag @cheese.picture_url %>
      </div>
          <%= link_to "Trouver un autre fromage", reload_page_path, id: "link-second-result" %>
          <br>
          <%= link_to "Modifier mes paramètres", root_path, id: "link-second-result-bis" %>
    <% else %>
      <p class="text-center mb-5">Pas de fromage pour vos critères de recherche...</p>
      <%= link_to "Modifier mes paramètres", root_path, id: "link-second-result" %>
    <% end %>
  </div>
</main>
<%= render "shared/navbar-bottom-default" %>